name: 👮 dev-validation

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  check-norminette:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 🛒 Install 42-norminette
        run: |
          python3 -m venv norminette_venv
          source norminette_venv/bin/activate
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install --upgrade norminette

      - name: 👮 Run norminette
        run: norminette **/*.[ch]

  check-compile-flags:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 🛒 Install build-essentials
        run: brew install gcc cmake make
      
      - name: 🚩 Compile with options -Wall -Wextra -Werror
        run: |
          mkdir build
          cd build
          cmake ..
          make