name: 👮 main-validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-norminette:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 🛒 Install 42-norminette
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install --upgrade norminette

      - name: 👮 Run norminette
        run: norminette **/*.[ch]

  check-compile-flags:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 🛒 Install build-essentials
        run: sudo apt-get install -y gcc make
      
      - name: 🚩 Compile with options -Wall -Wextra -Werror
        run: make